'use client';

import FusePageSimple from '@fuse/core/FusePageSimple';
import { styled } from '@mui/material/styles';
import Typography from '@mui/material/Typography';
import Paper from '@mui/material/Paper';
import Box from '@mui/material/Box';
import Chip from '@mui/material/Chip';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import LinearProgress from '@mui/material/LinearProgress';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import SearchIcon from '@mui/icons-material/Search';
import ShieldIcon from '@mui/icons-material/Shield';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';

const Root = styled(FusePageSimple)(({ theme }) => ({
	'&.FusePageSimple-scroll-content': {
		height: '100%',
	},
	'& .FusePageSimple-content': {
		backgroundColor: theme.vars.palette.background.default,
	},
}));

/* ------------------------------------------------------------------ */
/*  Data constants                                                     */
/* ------------------------------------------------------------------ */

const TECH_BADGES = [
	'Python', 'ReactJS', 'AWS Lambda', 'DynamoDB', 'KMS',
	'S3', 'Anthropic Claude', 'HMAC-SHA256',
];

interface SchemaColumn {
	name: string;
	type: string;
	notes: string;
}

const CATALOG_SCHEMA: SchemaColumn[] = [
	{ name: 'datasetId', type: 'VARCHAR', notes: 'PK — ds-001 through ds-012' },
	{ name: 'fileName', type: 'VARCHAR', notes: 'Source JSON file name' },
	{ name: 'displayName', type: 'VARCHAR', notes: 'Human-readable dataset name' },
	{ name: 'description', type: 'TEXT', notes: 'Auto-generated by LLM' },
	{ name: 'industryTag', type: 'ENUM', notes: '12 industries (FINTECH, HEALTHCARE, etc.)' },
	{ name: 'classification', type: 'ENUM', notes: 'PUBLIC, INTERNAL, CONFIDENTIAL, RESTRICTED' },
	{ name: 'regulatoryFlags', type: 'ARRAY', notes: 'GDPR, HIPAA, PCI-DSS, SOX, FERPA' },
	{ name: 'columns', type: 'ARRAY', notes: 'Column metadata with PII type and obfuscation rules' },
	{ name: 'rowCount', type: 'INT', notes: '500 rows per dataset' },
	{ name: 'qualityScore', type: 'INT', notes: '0-100, deducted by issue severity' },
	{ name: 'owner', type: 'VARCHAR', notes: 'Dataset steward' },
	{ name: 'publishedAt', type: 'DATETIME', notes: 'Catalog publication timestamp' },
];

const QUALITY_SCHEMA: SchemaColumn[] = [
	{ name: 'datasetId', type: 'VARCHAR', notes: 'FK → catalog' },
	{ name: 'overallScore', type: 'INT', notes: '0-100 (CRITICAL=-8, WARNING=-3, INFO=-1)' },
	{ name: 'issues', type: 'ARRAY', notes: 'Typed issues: NULL_RATE, DUPLICATE, OUTLIER, etc.' },
	{ name: 'columnHealth', type: 'ARRAY', notes: 'Per-column healthScore, nullRate, uniqueRate' },
	{ name: 'issueTypes', type: 'ENUM[]', notes: '11 types including SEMANTIC and BUSINESS_LOGIC' },
];

const OBFUSCATION_SCHEMA: SchemaColumn[] = [
	{ name: 'jobId', type: 'VARCHAR', notes: 'PK — obfuscation job identifier' },
	{ name: 'datasetId', type: 'VARCHAR', notes: 'FK → catalog' },
	{ name: 'status', type: 'ENUM', notes: 'COMPLETED, FAILED, RUNNING' },
	{ name: 'piiColumnsObfuscated', type: 'INT', notes: 'Number of PII columns processed' },
	{ name: 'rowsProcessed', type: 'INT', notes: 'Always 500 for demo datasets' },
	{ name: 'processingTimeMs', type: 'INT', notes: '800-3000ms range' },
	{ name: 'seedVersion', type: 'VARCHAR', notes: 'HMAC seed used (re-id key)' },
	{ name: 'reidentificationRequests', type: 'INT', notes: 'Approved re-id request count' },
];

interface LlmFeature {
	icon: typeof AutoAwesomeIcon;
	title: string;
	description: string;
}

const LLM_FEATURES: LlmFeature[] = [
	{
		icon: CloudUploadIcon,
		title: 'Automated Quality Check',
		description:
			'Combines 10 deterministic checks (null rates, duplicates, format validation) with 5 business logic rules and LLM-powered semantic analysis. Gracefully falls back to deterministic-only if LLM is unavailable.',
	},
	{
		icon: AutoAwesomeIcon,
		title: 'Metadata Generation',
		description:
			'LLM generates comprehensive column-level metadata — descriptions, PII classification, sensitivity levels, obfuscation rules, and example values. Uses max_tokens 8000 for full JSON coverage across all columns.',
	},
	{
		icon: SearchIcon,
		title: 'Ask DataVault',
		description:
			'Conversational catalog search powered by LLM. Ask questions like "Which datasets contain financial PII?" and get inline dataset cards with direct links. Understands industry context and regulatory implications.',
	},
	{
		icon: ShieldIcon,
		title: 'Obfuscation Rule Suggestion',
		description:
			'LLM analyzes column metadata and PII types to suggest optimal obfuscation strategies — format-preserving HMAC for IDs, consistent hashing for emails, redaction for SSNs. JSON-only response for direct application.',
	},
];

interface MetricStat {
	value: string;
	label: string;
	bg: string;
}

const KEY_METRICS: MetricStat[] = [
	{ value: '$1.2M', label: 'Annual Savings', bg: 'bg-green-50 dark:bg-green-950' },
	{ value: '99%', label: 'Metadata Accuracy', bg: 'bg-blue-50 dark:bg-blue-950' },
	{ value: '12', label: 'Industries Covered', bg: 'bg-purple-50 dark:bg-purple-950' },
	{ value: '99.9%', label: 'Service Availability', bg: 'bg-amber-50 dark:bg-amber-950' },
];

/* ------------------------------------------------------------------ */
/*  Sub-components                                                     */
/* ------------------------------------------------------------------ */

function SchemaTable({ title, columns }: { title: string; columns: SchemaColumn[] }) {
	return (
		<Box className="mb-8">
			<Typography variant="h6" className="mb-3 font-semibold">{title}</Typography>
			<TableContainer component={Paper} variant="outlined">
				<Table size="small">
					<TableHead>
						<TableRow sx={{ backgroundColor: 'action.hover' }}>
							<TableCell sx={{ fontWeight: 700 }}>Column</TableCell>
							<TableCell sx={{ fontWeight: 700 }}>Type</TableCell>
							<TableCell sx={{ fontWeight: 700 }}>Notes</TableCell>
						</TableRow>
					</TableHead>
					<TableBody>
						{columns.map((col) => (
							<TableRow key={col.name} hover>
								<TableCell>
									<code className="rounded bg-gray-100 px-1.5 py-0.5 text-sm dark:bg-gray-800">{col.name}</code>
								</TableCell>
								<TableCell>
									<span className="text-sm font-medium text-blue-700 dark:text-blue-400">{col.type}</span>
								</TableCell>
								<TableCell className="text-sm text-gray-600 dark:text-gray-400">{col.notes}</TableCell>
							</TableRow>
						))}
					</TableBody>
				</Table>
			</TableContainer>
		</Box>
	);
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
	return (
		<Box className="mb-16">
			<Typography variant="h4" className="mb-6 font-bold tracking-tight">{title}</Typography>
			{children}
		</Box>
	);
}

/* ------------------------------------------------------------------ */
/*  Main page                                                          */
/* ------------------------------------------------------------------ */

/**
 * DataOps Suite About page — system design overview, data catalog architecture,
 * obfuscation pipeline, quality scoring, and LLM enhancements.
 */
export default function AboutPage() {
	return (
		<Root
			scroll="content"
			content={
				<Box className="w-full">
					{/* Hero */}
					<Box
						className="flex flex-col items-center justify-center px-6 py-20 text-center text-white"
						sx={{
							background: 'linear-gradient(135deg, #7c3aed 0%, #2563eb 50%, #06b6d4 100%)',
						}}
					>
						<Typography variant="h3" className="mb-4 font-extrabold tracking-tight">
							DataOps Suite — Enterprise Data Management
						</Typography>
						<Typography variant="h6" className="mb-8 max-w-2xl font-light opacity-90">
							Conversational data catalog, automated metadata generation, and format-preserving obfuscation across 12 industries
						</Typography>
						<Box className="flex flex-wrap justify-center gap-2">
							{TECH_BADGES.map((badge) => (
								<Chip
									key={badge}
									label={badge}
									sx={{
										backgroundColor: 'rgba(255,255,255,0.2)',
										color: '#fff',
										fontWeight: 600,
										backdropFilter: 'blur(4px)',
										border: '1px solid rgba(255,255,255,0.3)',
									}}
								/>
							))}
						</Box>
					</Box>

					{/* Body */}
					<Box className="mx-auto max-w-5xl px-6 py-16 sm:px-10">
						{/* Problem Statement */}
						<Section title="Problem Statement">
							<Paper variant="outlined" className="p-6 sm:p-8" sx={{ borderRadius: 3 }}>
								<Typography variant="body1" className="mb-4 leading-relaxed text-gray-700 dark:text-gray-300">
									Amazon&apos;s PX Central Science team managed hundreds of datasets across
									12 industry verticals. Metadata was manually written, quality checks were
									ad-hoc, and PII obfuscation required custom scripts per dataset — creating
									bottlenecks that slowed data sharing, introduced compliance risks, and
									consumed 60% of the team&apos;s bandwidth on routine data management tasks.
								</Typography>
								<Typography variant="body1" className="leading-relaxed text-gray-700 dark:text-gray-300">
									DataOps Suite automates the entire data lifecycle: a 4-step Ingest Wizard
									handles upload, quality validation, metadata generation, and catalog
									publication. The Data Catalog provides searchable, browsable access with
									full schema documentation, quality reports, and lineage tracking. The
									Obfuscation Service applies format-preserving HMAC-SHA256 transformations
									to PII columns with deterministic, reversible results — enabling safe data
									sharing while maintaining referential integrity.
								</Typography>
							</Paper>
						</Section>

						{/* Architecture */}
						<Section title="System Architecture">
							<Paper variant="outlined" className="p-6 sm:p-8" sx={{ borderRadius: 3 }}>
								<Typography variant="body1" className="mb-4 leading-relaxed text-gray-700 dark:text-gray-300">
									The Ingest Wizard accepts CSV/JSON uploads (capped at 20 rows for LLM cost
									control), runs a hybrid quality pipeline (deterministic + LLM semantic checks),
									and generates column-level metadata via Anthropic Claude. Published datasets
									are persisted to the catalog with full provenance tracking.
								</Typography>
								<Typography variant="body1" className="mb-4 leading-relaxed text-gray-700 dark:text-gray-300">
									The Obfuscation Service uses HMAC-SHA256 via the Web Crypto API
									(crypto.subtle.sign) with a deterministic seed (DEMO_SEED_2024). In
									production, the seed would be a KMS Customer Master Key (CMK) with
									IAM-controlled access — the seed IS the re-identification key, so access
									control is the security boundary.
								</Typography>
								<Typography variant="body1" className="leading-relaxed text-gray-700 dark:text-gray-300">
									Format preservation ensures obfuscated data maintains the same structure
									as the original: emails remain valid email formats, phone numbers keep
									their digit patterns, SSNs preserve the XXX-XX-XXXX format, and names
									remain pronounceable strings. Running the same input twice always produces
									the same output (deterministic), enabling cross-dataset joins on obfuscated
									keys.
								</Typography>
							</Paper>
						</Section>

						{/* Data Model */}
						<Section title="Data Model">
							<SchemaTable title="Catalog Entries" columns={CATALOG_SCHEMA} />
							<SchemaTable title="Quality Reports" columns={QUALITY_SCHEMA} />
							<SchemaTable title="Obfuscation Jobs" columns={OBFUSCATION_SCHEMA} />
						</Section>

						{/* Quality Scoring */}
						<Section title="Quality Scoring Model">
							<Paper variant="outlined" className="p-6 sm:p-8" sx={{ borderRadius: 3 }}>
								<Box className="mb-6 rounded-lg p-4 text-center" sx={{ backgroundColor: 'action.hover' }}>
									<Typography sx={{ fontFamily: 'monospace', fontSize: '0.95rem', fontWeight: 600 }}>
										Score = 100 - (CRITICAL x 8) - (WARNING x 3) - (INFO x 1), clamped [0, 100]
									</Typography>
								</Box>
								<Box className="space-y-4">
									{[
										{ label: 'CRITICAL (-8 pts)', value: 100, color: '#ef4444', desc: 'Duplicate keys, severe null rates, schema violations' },
										{ label: 'WARNING (-3 pts)', value: 60, color: '#f59e0b', desc: 'Format inconsistencies, computed drift, outliers' },
										{ label: 'INFO (-1 pt)', value: 30, color: '#3b82f6', desc: 'Minor completeness gaps, style inconsistencies' },
									].map((tier) => (
										<Box key={tier.label}>
											<Box className="mb-1 flex items-baseline justify-between">
												<Typography variant="subtitle2" className="font-semibold">{tier.label}</Typography>
												<Typography variant="caption" className="font-bold" sx={{ color: tier.color }}>
													{tier.label.split(' ')[0]}
												</Typography>
											</Box>
											<LinearProgress
												variant="determinate"
												value={tier.value}
												sx={{
													height: 10, borderRadius: 5, backgroundColor: 'action.hover',
													'& .MuiLinearProgress-bar': { backgroundColor: tier.color, borderRadius: 5 },
												}}
											/>
											<Typography variant="caption" className="mt-0.5 text-gray-500 dark:text-gray-400">{tier.desc}</Typography>
										</Box>
									))}
								</Box>
							</Paper>
						</Section>

						{/* LLM Enhancements */}
						<Section title="LLM Enhancements">
							<Box className="grid gap-6 sm:grid-cols-2">
								{LLM_FEATURES.map((feat) => {
									const Icon = feat.icon;
									return (
										<Paper key={feat.title} variant="outlined" className="p-6" sx={{ borderRadius: 3 }}>
											<Box className="mb-3 flex items-center gap-2">
												<Icon sx={{ color: '#7c3aed' }} />
												<Typography variant="h6" className="font-semibold">
													{feat.title} <span className="text-purple-500">&#10022;</span>
												</Typography>
											</Box>
											<Typography variant="body2" className="mb-3 leading-relaxed text-gray-600 dark:text-gray-400">
												{feat.description}
											</Typography>
											<Typography variant="caption" className="italic text-gray-400 dark:text-gray-500">
												Represents how I would build this system today with LLM capabilities
											</Typography>
										</Paper>
									);
								})}
							</Box>
						</Section>

						{/* Key Metrics */}
						<Section title="Key Metrics">
							<Box className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
								{KEY_METRICS.map((m) => (
									<Paper
										key={m.label}
										variant="outlined"
										className={`flex flex-col items-center justify-center p-6 text-center ${m.bg}`}
										sx={{ borderRadius: 3 }}
									>
										<Typography variant="h4" className="mb-1 font-extrabold tracking-tight">{m.value}</Typography>
										<Typography variant="body2" className="font-medium text-gray-500 dark:text-gray-400">{m.label}</Typography>
									</Paper>
								))}
							</Box>
						</Section>
					</Box>
				</Box>
			}
		/>
	);
}
